baseURL: "https://docs.grumpy.systems/"
languageCode: "en-us"
title: "Docs - Grumpy"
theme: "learn"

# outputs:
#   - HTML
#   - RSS
#   - JSON

params:
  disableLandingPageButton: true
  disableNextPrev: true
  custom_css:
    - "css/fixes.css"
  customMermaidURL: "js/mermaid.min.js"

menu:
  shortcuts:
    - name: '<i class="fas fa-home">Main Site</i>'
      weight: 1
      url: "https://grumpy.systems"